### ISSUE TITLE
Donate button modal font size should be independent of root font size

### ISSUE THREAD

**Issue by osdiab** [everydotorg/donate-button#246] opened 2021-08-31 17:16 UTC
https://fundis.org/ implemented our donate button, but then because the document root sets the `font-size` to `10px` the donate button modal becomes really tiny.

Ideally even if the site has weird styles like that it should still look OK - the problem is that we use `rem` but that always reads off of the font size of the base `html` element.

Perhaps we should instead just use `px` font sizes - `em` font sizes are somewhat unpredictable (can still get messed up by underlying page styles, and varies based on parent styles), and while `px` isn't accessible it can still be adapted by browser magnification settings.

**Comment by martinbianchi** [comment] 2021-08-31 18:22
@osdiab I see, the problem is that we removed the shadow DOM from the v2 of the widget because it was unnecessary. I'm ok on moving everything to pixels or you think that using the Shadow DOM again will be a more robust solution?

**Comment by osdiab** [comment] 2021-09-01 20:03
That's not actually the problem, in v1 it also fails because the shadow DOM does not affect the value of `1rem` at all, it's still based on the base `html` element's style.

**Comment by martinbianchi** [comment] 2021-09-30 22:16
closed by #247

**Closed by martinbianchi** 2021-09-30 22:16 UTC
